const searchOptions = [
  {
    label: "General",
    options: [
      { value: "introduction", label: "Introduction" },
      { value: "technologies", label: "Technologies" },
    ],
  },
  {
    label: "By Domain",
    options: [
      { value: "healthTech", label: "Health Tech" },
      { value: "fashionTech", label: "Fashion Tech" },
      { value: "financeTech", label: "Finance Tech" },
      { value: "sportsTech", label: "Sports Tech" },
      { value: "agriTech", label: "Agri Tech" },
      { value: "enterpriseTech", label: "Enterprise Tech" },
      { value: "gamingTech", label: " Gaming Tech" },
      { value: "ecommerce", label: "Ecommerce" },
      { value: "bigDataTech", label: "Big Data Tech" },
      { value: "socialTech", label: "Social Tech" },
      { value: "streamingTech", label: "Streaming Tech" },
    ],
  },
  {
    label: "By Client",
    options: [
      { value: "cleartrip", label: "Clear Trip" },
      { value: "dorak", label: "Dorak" },
      { value: "ridaInternational", label: "Rida International" },
      { value: "betterClub", label: "Better Club" },
      { value: "practo", label: "Practo" },
      { value: "landmarkGroup", label: "Landmark Group" },
      { value: "nykaa", label: "Nykaa" },
      { value: "tailorAndCircus", label: "Tailor And Circus" },
      { value: "myntra", label: "Myntra" },
      { value: "zalora", label: "Zalora" },
      { value: "adityaBirlaGroup", label: "Aditya Birla Group" },
      { value: "acko", label: "Acko" },
      { value: "digitInsurance", label: "Digit Insurance" },
      { value: "pineLabs", label: "Pine Labs" },
      { value: "okCredit", label: "Ok Credit" },
      { value: "instamojo", label: "Instamojo" },
      { value: "decathlon", label: "Decathlon" },
      { value: "trrainCircle", label: "Trrain Circle" },
      { value: "efiSprinters", label: "Efi Sprinters" },
      { value: "extramile", label: "Extra Mile" },
      { value: "adda52", label: "Adda52" },
      { value: "growIndigo", label: "Grow Indigo" },
      { value: "udaan", label: "Udaan" },
      { value: "shopmatic", label: "Shopmatic" },
      { value: "crayon", label: "Crayon" },
      { value: "myGate", label: "My Gate" },
      { value: "bookMyShow", label: "Book My Show" },
    ],
  },
];

export { searchOptions };
